import Head from 'next/head';
import BenefitCard from '../components/BenefitCard';
import Icon from '../components/icon';
import Navbar from '../components/navbar';
import dynamic from 'next/dynamic';
import Carousel from 'react-multi-carousel';
const OwlCarousel = dynamic(() => import('react-owl-carousel'), { ssr: false });

import 'owl.carousel/dist/assets/owl.carousel.css';
import 'owl.carousel/dist/assets/owl.theme.default.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <script src='jquery.min.js'></script>
      </Head>
      <div className='hero-main'>
        <Navbar />
        <div className='container flex-row-b hero-inner'>
          <div className='herro1'>
            <h1 className='fw700 fs36 lh45'>
              Financial transfer pricing made easy
            </h1>
            <p className='fw500 fs20 lh30'>
              The most powerful and comprehensive financial transfer pricing
              software platform
            </p>
            <button className='btn btn-nav fw500 fs14 lh17'>
              Schedule a demo
            </button>

            <h2 className='fw500 fs14 lh17'>
              Accurate™ is used by multibillion dollar multinationals in over
              100 countries
            </h2>
          </div>
          <div className='w-100 herro1-rg'>
            <img src='Hero image.png' />
          </div>
        </div>
      </div>
      <div className='container'>
        <div className='benefit-main'>
          <h2 className='fw500 fs32 lh24'>Benefits</h2>
          <div className='benefit-inner'>
            <BenefitCard
              icon='c1'
              title='Achieve Full Compliance'
              description='Increase defensibility towards Tax Authroities worldwide by pricing and documenting financial transactions consistent with OECD guidance and best-practice financial theory'
            />
            <BenefitCard
              icon='c2'
              title='Save Time'
              description='Reduce time burden on in-house teams and eliminate coordination and waiting time associated with traditional advisory firms'
            />
            <BenefitCard
              icon='c3'
              title='Mitigate Risk'
              description='Monitor transactions in real-time, follow the audit trail and keep documents safe and organized in a single centralized platform'
            />
            <BenefitCard
              icon='c4'
              title='Facilitate Collabortion'
              description='Improve collaboration and visibility across internal departments with a centralized platform'
            />
            <BenefitCard
              icon='c5'
              title='Optimize Positions'
              description='Run multiple scenarios quickly for equally defensible but more efficient transactions'
            />
            <BenefitCard
              icon='c6'
              title='Increase Quality'
              description='Ensure precise results and documentation by eliminating the human error and inconsistency inherent in traditional manual pricing approaches'
            />
            <BenefitCard
              icon='c7'
              title='Reduce Controversy'
              description={`Avoid audits by pricing and documenting all intercompany financial transactions at arm's length no matter how small or large`}
            />
            <BenefitCard
              icon='c8'
              title='Gain Independence'
              description='Free up internal time and reduce dependence on external advisors'
            />
          </div>
        </div>
      </div>
      <div>
        <div className='features-main'>
          <h1 className='fw500 fs32 lh24'>Features</h1>
          <div className='car-main'>
            <OwlCarousel
              className='owl-theme collection-carousel'
              loop={true}
              dots={true}
              nav={true}
              navText={[
                "<img src='CaretCircleLeft.png'>",
                "<img src='CaretCircleRight.png'>",
              ]}
              responsive={{
                0: {
                  items: 1,
                },
                600: {
                  items: 1,
                },
                1000: {
                  items: 1,
                },
                10000: {
                  items: 1,
                },
              }}
            >
              <div className='item'>
                <h1>sd</h1>
              </div>
            </OwlCarousel>
          </div>
        </div>
      </div>
    </div>
  );
}
